#!/bin/bash
# SQL (INSERT statements) -> CSV converter
# Usage: sql_to_csv.sh <input.sql> <output.csv>
# Note: MVP parser supports INSERTs generated by dtconvert.

set -euo pipefail

if [ $# -lt 2 ]; then
  echo "Usage: $0 <input.sql> <output.csv>" >&2
  exit 1
fi

INPUT_FILE="$1"
OUTPUT_FILE="$2"

if [ ! -f "$INPUT_FILE" ]; then
  echo "Error: Input file not found: $INPUT_FILE" >&2
  exit 1
fi

SQL_CONVERT_BIN="$(dirname "$0")/../lib/converters/sql_convert"
if [ ! -x "$SQL_CONVERT_BIN" ]; then
  echo "Error: sql_convert helper not found or not executable: $SQL_CONVERT_BIN" >&2
  echo "Hint: run 'make' to build helper converters" >&2
  exit 1
fi

"$SQL_CONVERT_BIN" sql-to-csv "$INPUT_FILE" "$OUTPUT_FILE"
